# a simple Artifacts.toml file
[tsz_example]
git-tree-sha1 = "c9634624e033a452d13759bd3c2612df1692a067"
lazy = true

    [[tsz_example.download]]
    url = "https://github.com/WebSky-CITA/XGPaint.jl/releases/download/tsz_example/tsz_example.tar.gz"
    sha256 = "33242449b9a67e9c21e243e80c61bc00123ffc3325cd109aa1f045bf7d798e50"


[tsz_test_map]
git-tree-sha1 = "33c94a68b66fc36ede1d72d1d2a6d55b30a67a7c"
lazy = true

    [[tsz_test_map.download]]
    url = "https://github.com/WebSky-CITA/XGPaint.jl/releases/download/tsz_example/test_tsz_map.tar.gz"
    sha256 = "401d903b4d145c2eef9ff9666adfb4ef7b2b3a3a0cbcb990a630e3a78a426735"

