[deps]
Cosmology = "76746363-e552-5dba-9a5a-cef6fa9cc5ab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Healpix = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
Pixell = "d4cbf8b2-a14f-4080-9f5e-d5a64ada768e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
XGPaint = "af630e4a-6754-4ec2-ab8a-f9f8b9ebafbf"
